### ISSUE TITLE
Easy popup

### ISSUE THREAD

**Issue by reagle** [jobiewong/espanso-emojis#8]
Consider creating a single trigger for all expansions so you can get an easy emoji popup:

```
matches:
  - triggers: [":emo", ":grinning:"]
    label: ":grinning:"
    replace: "\U0001F600"
  - triggers: [":emo", ":smiley:"]
    label: ":smiley:"
    replace: "\U0001F603"
  - triggers: [":emo", ":smile:"]
    label: ":smile:"
    replace: "\U0001F604"
```
